#Makefile generated by amake
#On Thu Aug 17 11:55:23 2017
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -pthread 
LIBS=-lpcap -lcurses 
OBJS=$(OBJDIR)/settings.o $(OBJDIR)/main.o $(OBJDIR)/packet_stats.o $(OBJDIR)/async_log.o $(OBJDIR)/proc.o $(OBJDIR)/name_res.o $(OBJDIR)/cap_mgr.o 
EXEC=nettop
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/settings.o: src/settings.cpp src/settings.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/settings.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/utils.h src/cap_mgr.h src/mt_list.h \
 src/packet_stats.h src/addr_t.h src/proc.h src/async_log.h \
 src/name_res.h src/settings.h src/epoll_stdin.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/packet_stats.o: src/packet_stats.cpp src/packet_stats.h src/addr_t.h \
 src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/packet_stats.cpp -c -o $@

$(OBJDIR)/async_log.o: src/async_log.cpp src/async_log.h src/mt_list.h \
 src/name_res.h src/addr_t.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/async_log.cpp -c -o $@

$(OBJDIR)/proc.o: src/proc.cpp src/proc.h src/packet_stats.h src/addr_t.h \
 src/async_log.h src/mt_list.h src/name_res.h src/utils.h src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/proc.cpp -c -o $@

$(OBJDIR)/name_res.o: src/name_res.cpp src/name_res.h src/addr_t.h src/mt_list.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/name_res.cpp -c -o $@

$(OBJDIR)/cap_mgr.o: src/cap_mgr.cpp src/cap_mgr.h src/mt_list.h src/packet_stats.h \
 src/addr_t.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/cap_mgr.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

